"""migration 3

Revision ID: 146c4655a93f
Revises: 9351308382c0
Create Date: 2022-12-20 03:23:03.177995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146c4655a93f'
down_revision = '9351308382c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dislikes')
    # ### end Alembic commands ###
