"""migration 2

Revision ID: 9351308382c0
Revises: 7054a974c086
Create Date: 2022-12-20 01:45:03.623178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9351308382c0'
down_revision = '7054a974c086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislikes', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=False))

    op.drop_table('Likes')
    # ### end Alembic commands ###
