"""initial migration

Revision ID: bb0ed19020db
Revises: 707805b19388
Create Date: 2022-11-02 19:00:30.173269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0ed19020db'
down_revision = '707805b19388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'status')
    # ### end Alembic commands ###
