"""empty message

Revision ID: 914b3991c1c9
Revises: 
Create Date: 2022-11-13 20:19:37.611160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914b3991c1c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_text'), 'idea', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_text'), table_name='idea')
    op.drop_table('idea')
    # ### end Alembic commands ###
